#!/usr/bin/env zsh


# default editor
export EDITOR=vim

export PATH="/usr/local/bin:${PATH}"
export PATH="/sbin:${PATH}"
export PATH="${HOME}/bin:${PATH}"
export PATH="${HOME}/usr/bin:${PATH}"
export PATH="${PATH}:/usr/sbin"
export GOPATH="${HOME}/.go"

if [ -f "${HOME}/Library/Haskell/bin" ]; then
    export PATH="${PATH}:${HOME}/Library/Haskell/bin"
fi

export ZSHD_PATH="${HOME}/.zsh.d"


# fix ssh sign useing the key
# https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/201786
export SSH_AUTH_SOCK=0

#xcode 4 bullshit -
#http://stackoverflow.com/questions/5944332/broken-pipe-error-when-using-pip-to-install-pycrypto-on-mac-os-x
export ARCHFLAGS='-arch i386 -arch x86_64'

export TZ="America/Los_Angeles"
export HOSTNAME="`hostname`"
export PAGER='less'
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
export LC_CTYPE=C
export DISPLAY=:0

if [ $SSH_TTY ]; then
  MUTT_EDITOR=vim
else
  MUTT_EDITOR=emacsclient.emacs-snapshot
fi

unsetopt ALL_EXPORT

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
     precmd () {print -Pn "\e]0;%n@%m: %~\a"}
        ;;
esac

autoload colors 
colors
autoload -U compinit
compinit

SYS_SNIPPLET=/usr/local/share/zsh/site-functions

if [ -d $SYS_SNIPPLET ]; then
    for zshrc_snipplet in $SYS_SNIPPLET/* ; do
        source $zshrc_snipplet
    done
fi
unset zshrc_snipplet
