#!/usr/bin/env zsh
export GOPATH="${HOME}/.go"
export GOROOT=/usr/local/go
export PATH=$PATH:$GOPATH/bin


function relative_go()
{
    if [ -d `pwd`/.go ]; then
        export GOPATH=`pwd`/.go
    fi
}

#chpwd_functions+=(relative_go)
