#!/usr/bin/env zsh

if [[ -x `which git` ]]; then
    function __prompt_git()
    {
        local git_dir ref br top;
        git_dir=$(git rev-parse --git-dir 2> /dev/null) || return
        ref=$(git symbolic-ref HEAD 2> /dev/null) || return
        br=${ref#refs/heads/}
        top=$(cat $git_dir/patches/$br/current 2>/dev/null) \
        && top="/$top"
        echo "[$br$top]"
    }
fi
