#!/use/bin/env zsh

AGENT_FILE="${TMPPREFIX}-${USER}-agent-env"

ps ux | grep ssh-agent | grep $USER | egrep "[s]sh-agent" | egrep -vq grep

if [[ $? != 0 ]]; then
    echo "creating ssh-agent in $AGENT_FILE"
    if [[ -f $AGENT_FILE ]]; then
        rm $AGENT_FILE
    fi
    ssh-agent | grep -v "^echo" > $AGENT_FILE
fi

source $AGENT_FILE
